import { Room } from './types';

export const mockRooms: Room[] = [
  {
    id: 'room-001',
    roomNumber: 'A-101',
    block: 'A',
    floor: '1',
    sharingType: 1,
    roomClass: 'Premium',
    totalBeds: 1,
    availableBeds: 1,
    pricePerSemester: 28000,
    amenities: ['Study Table', 'Wardrobe', 'Bookshelf', 'Fan', 'Power Backup', 'Wi-Fi'],
    status: 'available',
    floorArea: 180,
    windowFacing: 'East',
    attachedBathroom: true,
    description: 'Spacious single-occupancy room with attached bathroom and east-facing windows for natural morning light.',
  },
  {
    id: 'room-002',
    roomNumber: 'A-102',
    block: 'A',
    floor: '1',
    sharingType: 2,
    roomClass: 'Standard',
    totalBeds: 2,
    availableBeds: 1,
    pricePerSemester: 18500,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Power Backup', 'Wi-Fi'],
    status: 'limited',
    floorArea: 220,
    windowFacing: 'West',
    attachedBathroom: false,
    description: 'Double-sharing room with ample natural light and shared bathroom on the same floor.',
  },
  {
    id: 'room-003',
    roomNumber: 'A-201',
    block: 'A',
    floor: '2',
    sharingType: 3,
    roomClass: 'Standard',
    totalBeds: 3,
    availableBeds: 2,
    pricePerSemester: 14000,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Wi-Fi'],
    status: 'available',
    floorArea: 280,
    windowFacing: 'North',
    attachedBathroom: false,
    description: 'Triple-sharing room on the second floor with good ventilation and shared bathroom facilities.',
  },
  {
    id: 'room-004',
    roomNumber: 'A-202',
    block: 'A',
    floor: '2',
    sharingType: 4,
    roomClass: 'Economy',
    totalBeds: 4,
    availableBeds: 3,
    pricePerSemester: 10500,
    amenities: ['Study Table', 'Fan', 'Wi-Fi'],
    status: 'available',
    floorArea: 320,
    windowFacing: 'South',
    attachedBathroom: false,
    description: 'Economy quad-sharing room, ideal for students looking for affordable hostel accommodation.',
  },
  {
    id: 'room-005',
    roomNumber: 'B-101',
    block: 'B',
    floor: '1',
    sharingType: 1,
    roomClass: 'Standard',
    totalBeds: 1,
    availableBeds: 1,
    pricePerSemester: 22000,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Power Backup', 'Wi-Fi', 'Bookshelf'],
    status: 'available',
    floorArea: 160,
    windowFacing: 'East',
    attachedBathroom: false,
    description: 'Single-occupancy standard room in Block B with power backup and a quiet study environment.',
  },
  {
    id: 'room-006',
    roomNumber: 'B-102',
    block: 'B',
    floor: '1',
    sharingType: 2,
    roomClass: 'Premium',
    totalBeds: 2,
    availableBeds: 0,
    pricePerSemester: 24000,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Power Backup', 'Wi-Fi', 'Attached Bathroom'],
    status: 'full',
    floorArea: 260,
    windowFacing: 'South',
    attachedBathroom: true,
    description: 'Premium double-sharing room with attached bathroom. Currently fully occupied.',
  },
  {
    id: 'room-007',
    roomNumber: 'B-201',
    block: 'B',
    floor: '2',
    sharingType: 3,
    roomClass: 'Economy',
    totalBeds: 3,
    availableBeds: 1,
    pricePerSemester: 11500,
    amenities: ['Study Table', 'Fan'],
    status: 'limited',
    floorArea: 270,
    windowFacing: 'West',
    attachedBathroom: false,
    description: 'Budget-friendly triple-sharing room. Only 1 bed remaining — book soon.',
  },
  {
    id: 'room-008',
    roomNumber: 'B-202',
    block: 'B',
    floor: '2',
    sharingType: 4,
    roomClass: 'Standard',
    totalBeds: 4,
    availableBeds: 2,
    pricePerSemester: 13000,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Wi-Fi'],
    status: 'available',
    floorArea: 340,
    windowFacing: 'North',
    attachedBathroom: false,
    description: 'Standard quad-sharing room with good amenities and north-facing windows.',
  },
  {
    id: 'room-009',
    roomNumber: 'C-101',
    block: 'C',
    floor: '1',
    sharingType: 2,
    roomClass: 'Economy',
    totalBeds: 2,
    availableBeds: 2,
    pricePerSemester: 13500,
    amenities: ['Study Table', 'Fan', 'Wi-Fi'],
    status: 'available',
    floorArea: 200,
    windowFacing: 'East',
    attachedBathroom: false,
    description: 'Affordable double-sharing room in the new C Block with ground floor convenience.',
  },
  {
    id: 'room-010',
    roomNumber: 'C-102',
    block: 'C',
    floor: '1',
    sharingType: 1,
    roomClass: 'Economy',
    totalBeds: 1,
    availableBeds: 1,
    pricePerSemester: 16000,
    amenities: ['Study Table', 'Fan', 'Wi-Fi', 'Wardrobe'],
    status: 'available',
    floorArea: 145,
    windowFacing: 'West',
    attachedBathroom: false,
    description: 'Economy single room — great value for students who prefer privacy on a budget.',
  },
  {
    id: 'room-011',
    roomNumber: 'C-201',
    block: 'C',
    floor: '2',
    sharingType: 4,
    roomClass: 'Premium',
    totalBeds: 4,
    availableBeds: 1,
    pricePerSemester: 16500,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Power Backup', 'Wi-Fi', 'Mini Fridge'],
    status: 'limited',
    floorArea: 380,
    windowFacing: 'South',
    attachedBathroom: true,
    description: 'Premium quad-sharing room with attached bathroom and mini fridge — rare availability.',
  },
  {
    id: 'room-012',
    roomNumber: 'D-101',
    block: 'D',
    floor: '1',
    sharingType: 3,
    roomClass: 'Premium',
    totalBeds: 3,
    availableBeds: 2,
    pricePerSemester: 19500,
    amenities: ['Study Table', 'Wardrobe', 'Fan', 'Power Backup', 'Wi-Fi', 'Attached Bathroom', 'Mini Fridge'],
    status: 'available',
    floorArea: 300,
    windowFacing: 'East',
    attachedBathroom: true,
    description: 'Premium triple-sharing in D Block with attached bathroom, mini fridge and power backup.',
  },
];

export const blocks = ['A', 'B', 'C', 'D'];
export const floors = ['1', '2', '3'];